export const GETCATENAVDATA = 'getCateNavData'
export const GETINDEXCATEMODULE = 'getIndexCateModule'
export const GETINDEXDATA = 'getIndexData'
export const GETCATELISTS = 'getCateLists'
export const GETSEARCHVIEWINIT = 'getSearchViewInit'
export const GETSEARCHKEYWORD = 'getSearchKeyWord'
export const GETNAVWRAP = 'getNavWrap'
export const GETMANUAL = 'getManual'